config/routes.rb
Rails.application.routes.draw do
  resources :players
  resources :battles
  
  get 'battles/new'

  root 'battles#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/battle.rb
class Battle < ActiveRecord::Base
    require 'benchmark'
    attr_reader :right_answer, :math_sample, :answer_is_corrects

    has_many :battles_players
    has_many :players, through: :battles_players

    
    def check_user_answer
        self.check_timer
        user_answer = self.user_answer 
        system_answer = self.system_answer
        if user_answer == system_answer
            self.check_time_limit
            self.players.first[:game] == TRUE ? self.rp_points -= @damage : self.lp_points -= @damage
            self.check_game_progres
        else
            update(status: "uncorrect_answ")
        end
       
    end

    def saved_answer
        params.require(:battle).permit(:answer)
    end

    def change_turn_to_move

        if self.players.first[:game] == true 
            self.players.first.update(game: false) 
            self.players.last.update(game: true) 
        else
            self.players.first.update(game: true) 
            self.players.last.update(game: false) 
        end
    end

    def math_sample_generator
        exm = [rand(100), "", rand(100), "", rand(100)]
        
        exm[0] > exm[2] ? exm[1] = '-' : exm[1] = '+'  
        exm[2] < exm[4] ? exm[3] = '+' : exm[3] = '-'

        calculated = exm[0]
        exm[1] == '-' ? calculated -= exm[2] : calculated +=  exm[2]
        exm[3] == '-' ? calculated -= exm[4] : calculated +=  exm[4]
        @right_answer = calculated

        @math_sample  = ""
        6.times {|i| @math_sample << "#{exm[i]} "}
    end

    private

    def check_game_progres
        if self.lp_points <= 0
            update(lp_points: 0)
            self.players.first.update(loss: (self.players.first[:loss] + 1))
            self.players.last.update(win: (self.players.last[:win] + 1))
            update(status: "game_over")
        elsif self.rp_points <= 0
            update(rp_points:  0)
            self.players.last.update(loss: (self.players.last[:loss] + 1))
            self.players.first.update(win: (self.players.first[:win] + 1))
            update(status: "game_over")
        end
    end

    def check_timer
        time = (Time.now.utc - self.was_ready_at).to_i
        if time >= 20
            @damage = 0
        else
            @damage = (20 - time)
        end
    end

    def check_time_limit
        if @damage == 0
            update(status: "too_long")
        else
            update(status: "correct_answer",  damage: @damage)
        end
    end

    # first - lp, last - rp

    

end 

app/models/battles_player.rb
class BattlesPlayer < ActiveRecord::Base
    belongs_to :player
    belongs_to :battle

    
end

app/models/player.rb
class Player < ApplicationRecord
    validates :name, length: { minimum: 2,
        massage: "%{count} characters is the maximum allowed" }

    has_many :battles_players
    has_many :battles, through: :battles_players

    
end

app/models/test.rb
class Test < ApplicationRecord
    validates_presence_of :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/battles_controller.rb
class BattlesController < ApplicationController
    before_action :set_starter_setting, only: [ :create ]
    before_action :current_battle, only: [ :show, :edit, :update, :destroy ]
    add_flash_types :error

    def index
        @battles = Battle.all
    end

    def show
        @battle  = Battle.find(params[:id])
        
    end

    def new
        @battle = Battle.new
    end

    def create
        if @battle.save
            @battle.update(status: "first_move")
            redirect_to @battle
        else
            flash.now[:error] = "Ім'я  гравця має містити не менше двох символів."
            render :new 
        end
    end

    def edit
        @battle.update(was_ready_at: Time.now.utc)
        @battle.math_sample_generator
        @battle.update(system_answer: @battle.right_answer)
    end  

    def update
        @battle.update(user_answer: saved_answer[:answer])
        @battle.check_user_answer
        @battle.change_turn_to_move
    
        respond_to do |format|
            if @battle.save
                format.html { redirect_to @battle, action: 'show'}
            else
                format.html { render :new, status: :unprocessable_entity }
            end
          end        
    end

    private

    def set_starter_setting
        @battle = Battle.new 
        @battle[:has_players] = "#{battle_params[:left_player]} - #{battle_params[:right_player]}"
        @battle[:system_answer] = 1010 
        
        @battle.players << Player.create(name: battle_params[:left_player], game: TRUE)
        @battle.players << Player.create(name: battle_params[:right_player])

    end

    def current_battle
        @battle = Battle.find(params[:id])
      end

    def battle_params
       params.require(:battle).permit(:left_player, :right_player)
    end

    def saved_answer
        params.require(:battle).permit(:answer)
    end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: %i[ show edit update destroy ]

  # GET /players or /players.json
  def index
    @players = Player.all
  end

  # GET /players/1 or /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  
  # POST /players or /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player}
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1 or /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player}
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def player_params
      params.require(:player).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/battles/_answer_form.html.erb
<div>
  <%= form_with(model: battle) do |form| %>
    <div class="field">
      <b>=</b><br>
      <%= form.text_field :answer, class: 'form-control', autofocus: true, :rows => 10 %>
      <br> 
      <%= form.submit :'Удар!', class: 'btn btn-info', style: 'margin-top: 10px; '%>
    </div>
  <% end %>
</div>

app/views/battles/_info_board.html.erb
<%@battle.players.first[:game] == false ?  player  = @battle.players.first[:name] : player  = @battle.players.last[:name]%>
<%if  @battle[:status] == "first_move"%>
  <h4>Бій розпочато!</h4>
<%elsif @battle[:status] == "correct_answer"%>
  <div class="alert alert-success">
    <% damage = @battle[:damage] %>
    <p><%=player%>, вірно! <br>
    Сила удару: <%= damage%></p>
    <p>Затрачено часу: <%=20 - damage%> сек.</p>
  </div>
<%elsif @battle[:status] == "too_long"%>
  <div class="alert alert-warning">
      <p><%=player%>, ти цілився довше 20-и секунд.</p>
      <p>Удар не зараховано</p>
    </div>
<%elsif @battle[:status] == "uncorrect_answ"%>
  <div class="alert alert-danger">
      <p><%=player%>, ти промахнувся.<br>
      Правильна відповідь:  <%= @battle[:system_answer]%></p>
    </div>
<%end%>

app/views/battles/_registration_form.html.erb
<%= form_with(model: battle) do |form| %>

  <div>
    <%= form.label :left_player, 'Гравець зліва' %>
    <%= form.text_field :left_player, class: 'form-control' %>
    <br>
    <%= form.label :right_player , 'Гравець справа', style: 'margin-top: 10px; '%>
    <%= form.text_field :right_player, class: 'form-control' %>

  </div>

  <div class="actions">
    <%= form.submit :"Далі", class: 'btn btn-info', style: 'margin-top: 10px; '%>
  </div>
<% end %>

app/views/battles/edit.html.erb
 <div class="col-lg-12">
          <div class="col-lg-4 l_player"> 
            <div class="centered"><h2><%=@battle.players.first.name%></h2></div>
            <%= image_tag 'left_p.png' %> 
            <% lp_points = @battle.lp_points%>
            <div class="progress">
              <div class="progress-bar" role="progressbar" style="width: <%=lp_points%>%;"  aria-valuenow=<%=lp_points.to_s%> aria-valuemin="0" aria-valuemax="100">
              <%=lp_points %>
              </div>
            </div>
          </div>
          <div class="col-lg-4 centered">
            <h2>VS</h2>
            <%if @battle[:status] == "game_over"%>
                <% @battle.players.where(game: FALSE).name %>
            <%else%>
                <div class="alert alert-info">
                <b><%=@battle.math_sample %></b> 
                <%# <%=@battle.right_answer %> 
                
                <%= render 'answer_form', battle: @battle %>
            </div>
            <%end%>
          </div>
          <div class="col-lg-4 r_player"> 
            <div class="centered"><h2><%=@battle.players.last.name%></h2></div>
            <%= image_tag 'right_p.png'  %>
            <% rp_points = @battle.rp_points%>
            <div class="progress">
              <div class="progress-bar" role="progressbar" style="width: <%=rp_points%>%;"  aria-valuenow=<%=rp_points.to_s%> aria-valuemin="0" aria-valuemax="100">
              <%=rp_points %>
              </div>
            </div>
          </div>
        </div><!--/lg-12-->





 

app/views/battles/index.html.erb
<div class="col-md-12">
<h3>Битви</h3>

<table class="table">
  <thead class="centered">
    <tr>
      <th class="centered">id</th>
      <th class="centered">Гравець справа</th>
      <th class="centered">Гравець зліва</th>
      <th class="centered">Життя гравця зліва</th>
      <th class="centered">Життя гравця справа</th>
    </tr>
  </thead>

  <tbody class="centered">
    <% @battles.each do |battle| %>
      <%if battle.status == "game_over"%>
        <tr class='alert alert-success'>
      <%else%>
        <tr>
      <%end%>
        <td class="boxhead"><%= link_to battle.id, battle_path(battle)%></td>
        <%id = battle.players.first[:id]%>
        <td class="boxhead"><%= link_to battle.players.first[:name], "/players/#{id}"%></td>
        <%id = battle.players.last[:id]%>
        <td class="boxhead"><%= link_to battle.players.last[:name], "/players/#{id}"%></td>
        <td><%= battle.lp_points %></td>
        <td><%= battle.rp_points %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>

  
  

app/views/battles/new.html.erb
 <div class="col-lg-12">
          <div class="col-lg-4 l_player"> 
            <%= image_tag 'left_p.png' %> 
          </div>
            <div class="col-lg-4 centered"> 
                <div class="alert alert-info">
                  Будь ласка введіть імена гравців
                </div>
                <div class="entered " alt="CenterSide"><%= render 'registration_form', battle: @battle %></div>
            </div>
          <div class="col-lg-4 r_player"> 
            <%= image_tag 'right_p.png'  %>
          </div>
        </div><!--/lg-12-->

app/views/battles/show.html.erb
 <div class="col-lg-12">
          <div class="col-lg-4 l_player"> 
            <div class="centered"><h2><%=@battle.players.first.name%></h2></div>
            <%= image_tag 'left_p.png', :class => "style_image" %> 
            <% lp_points = @battle.lp_points%>
            <div class="progress">
              <div class="progress-bar" role="progressbar" style="width: <%=lp_points%>%;"  aria-valuenow=<%=lp_points.to_s%> aria-valuemin="0" aria-valuemax="100">
                <%=lp_points %>
              </div>
            </div>
          </div>
          <div class="col-lg-4 centered">
            <h2>VS</h2>
            <%if @battle[:status] == "game_over"%>
            <div class="alert alert-success">
              <p><%= @battle.players.find_by(game: false)[:name] %>, вітаю! Ти переміг</p>
            </div>
                
            <%else%>
                <%= render 'info_board'%>
                <div class="alert alert-info">
                    <p><b>Хід гравця <%= @battle.players.find_by(game: true)[:name] %></b></p>
                    <p>У тебе є  20 секунд на удар.<br>Ти готовий?</p>
                </div>
                <%= link_to 'Так!', edit_battle_path(@battle), class: 'btn btn-info', style: 'text-devoration: none; '%>
            <%end%>
          </div>
          <div class="col-lg-4 r_player"> 
            <div class="centered"><h2><%=@battle.players.last.name%></h2></div>
            <%= image_tag 'right_p.png', :class => "style_image"%>
            <% rp_points = @battle.rp_points%>
            <div class="progress">
              <div class="progress-bar" role="progressbar" style="width: <%=rp_points%>%;"  aria-valuenow=<%=rp_points.to_s%> aria-valuemin="0" aria-valuemax="100">
              <%=rp_points %>
              </div>
            </div>
          </div>
        </div><!--/lg-12-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>MathGO</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
 
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="navbar-collapse collapse navbar-responsive-collapse">
      
        <ul class="nav navbar-nav col-md-12">
          <h1 class="logo">MathGO</h1>
          <li class="btn col-md-4 head-btn"><%= link_to 'Розпочати бій', new_battle_path %></li>
          <li class="btn col-md-4 head-btn"><%= link_to 'Гравці', players_path %></li>
          <li class="btn col-md-4 head-btn"><%= link_to 'Бої', battles_path %></li>
          </ul>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <%= bootstrap_flash %>  
        <%= yield %>
      </div><!--/row-->
      
      <footer>
        
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/welcome.html.erb
<a class="btn col-md-4 head-btn"> 
<%= link_to 'Новий бій', new_battle_path %>
</a>

app/views/players/_form.html.erb
<%= form_with(model: player) do |form| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
        <% player.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<div class="col-md-12">
<h3>Гравці</h3>

<table class="table">
  <thead class="centered">
    <tr>
      <th class="centered">Ім'я гравця</th>
      <th class="centered">Всього боїв</th>
      <th class="centered">Перемог</th>
      <th class="centered">Програшів</th>
    </tr>
  </thead>

  <tbody class="centered">
    <% @players.each do |player| %> 
      <tr>
        <td><%= player.name %></td>
        <td><%= player.total_battles %></td> 
        <td><%= player.win %></td>
        <td><%= player.loss %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>

  

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<div class="col-md-12">
<h3>Гравці</h3>

<table class="table">
  <thead class="centered">
    <tr>
      <th class="centered">Ім'я гравця</th>
      <th class="centered">Всього боїв</th>
      <th class="centered">Перемог</th>
      <th class="centered">Програшів</th>
    </tr>
  </thead>

  <tbody class="centered">
      <tr>
        <td><%= @player.name %></td>
        <td><%= @player.total_battles %></td> 
        <td><%= @player.win %></td>
        <td><%= @player.loss %></td>
      </tr>
  </tbody>
</table>

</div>

  